
.PHONY:$(preobj)
preobj = $(LIBHOME)/input.pre
LIB = $(LIBHOME)/libinput.so
SRC =  input.cc inputFileReader.cc IDBAccessor.cc inputEditor.cc section.cc sectionParamShape.cc sectionParam.cc IDB.cc sectionType.cc sectionParamType.cc

include ../variables/makefile.base

preobj:  
	
